export const prevCodeName = "prev_code"

export const startNameParam = "start"
export const endNameParam = "end"
export const productIdNameParam = "productId"
export const productIdsNameParam = "productIds"
export const userIdNameParam = "userId"
export const categoryNameParam = "category"
export const keywordNameParam = "keyword"
export const filtersNameParam = "filters"

export const productIdName = "id"
export const colorName = "color"
export const earSideName = "earSide"
export const guaranteeName = "guarantee"
export const nameName = "name"
export const brandName = "brand"
export const priceName = "price"
export const imageURLName = "imageURL"
export const productDescriptionName = "description"
export const adaptationRangeName = "adaptation_range"
export const earLocationName = "ear_location"
export const levelOfDiscretionName = "level_of_discretion"
export const degreeOfLossName = "degree_of_loss"
export const usesName = "uses"
export const includeName = "INCLUDE" 
export const waterDustResistanceName = "water_dust_resistance" //

export const bargainCodeName = "code"
export const bargainTitleName = "title"
export const bargainDescriptionName = "description"

export const noveltyIdName = "id"
export const noveltyTitleName = "title"
export const noveltyDescriptionName = "description"
export const promotionalImageName = "promotional_image"