export const UNIT_TEST_TAG = "UNIT"
export const INTEGRATION_TEST_TAG = "INTEGRATION"
export const SYSTEM_TEST_TAG = "E2E"
export const COMPONENT_TEST_TAG = "COMPONENT"
export const API_TEST_TAG = "API"