export const startNameParam = "start"
export const endNameParam = "end"
export const productIdNameParam = "productId"
export const productIdsNameParam = "productIds"
export const userIdNameParam = "userId"
export const categoryNameParam = "category"
export const keywordNameParam = "keyword"
export const filtersNameParam = "filters"

export const productIdName = "id"
export const colorTextName = "color_name"
export const colorHexName = "color_hex"
export const earSideName = "earSide"
export const nameName = "name"
export const categoryName = "category"
export const brandName = "brand"
export const priceName = "price"
export const imageURLName = "imageURL"
export const productDescriptionName = "description"
export const adaptationRangeName = "adaptation_range"
export const earLocationName = "ear_location"
export const levelOfDiscretionName = "level_of_discretion"
export const degreeOfLossName = "degree_of_loss"
export const usesName = "uses"
export const includeName = "INCLUDE" 
export const dustWaterResistanceName = "dust_water_resistance"
export const hasDustWaterResistanceName ="YES"
export const earphoneShapeName = "earphone_shape"

export const bargainIdName = "id"
export const bargainCodeName = "code"
export const bargainTitleName = "title"
export const bargainDescriptionName = "description"

export const noveltyIdName = "id"
export const noveltyTitleName = "title"
export const noveltyDescriptionName = "description"
export const promotionalImageName = "promotional_image"

export const userIdName = "user_id"
export const userNameName = "user_mame"
export const userFirstName = "user_first_name"
export const phoneNumberName = "phone_number"
export const emailName = "email"
export const addressName = "address"
export const audiometryFileName = "audiometry_file"

export const contactEmailName = "email"
export const contactSubjectName = "subject"
export const contactBodyName = "body"
