import type { Metadata } from "next";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeToggle from "./components/common/themeToggle";
import Header from "./components/common/header";
import Footer from "./components/common/footer";
import {
  ClerkProvider
} from "@clerk/nextjs";
import { esES } from "@clerk/localizations";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const localization = {
  signUp: {
    start: {
      title: 'Bienvenid@ al club',
      subtitle: 'Registrate ahora en nuetra web para aprovecharte de todas las ventajas',
      actionText: '¿Tienes ya una cuenta?',
      actionLink: 'Inicia sesión ahora mismo.',
    },
    emailLink: {
      title: 'Verifica tu email',
      subtitle: 'Así podrás empezar a usar la web al completo',
      formTitle: 'Enlace de verificación',
      formSubtitle: 'Usa el enlace de verificación que te hemos enviado al correo',
      resendButton: "¿No has recibido ningún enlace? Te lo enviamos de vuelta.",
      verified: {
        title: 'Registro completado',
      },
      loading: {
        title: 'Registrandote...',
      },
      verifiedSwitchTab: {
        title: 'Tu correo ha sido verificado',
        subtitle: 'Volver a la pestaña recién abierta para continuar',
        subtitleNewTab: 'Volver a la pestaña anterior para continuar',
      },
    },
    emailCode: {
      title: 'Verifica tu email',
      subtitle: 'Ahí podrás revisar el código de verificación',
      formTitle: 'Código de verificación',
      formSubtitle: 'Introduce el código que te hemos enviado al correo',
      resendButton: "¿No has recibido ningún código? Te lo enviamos de vuelta.",
    },
    phoneCode: {
      title: 'Verifica tu teléfono',
      subtitle: 'Ahí podrás revisar el código de verificación',
      formTitle: 'Código de verificación',
      formSubtitle: 'Introduce el código que te hemos enviado al teléfono',
      resendButton: "¿No has recibido ningún código? Te lo enviamos de vuelta.",
    },
    continue: {
      title: 'Rellena los campos vacíos del formulario',
      subtitle: 'Así podrás empezar a usar la web al completo',
      actionText: '¿Tienes ya una cuenta?',
      actionLink: 'Iniciar Sesión',
    },
  },
  formFieldLabel__emailAddress: 'Correo electrónico',
  formFieldLabel__password: 'Contraseña',
  formButtonPrimary: 'Continuar',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider localization={localization}>
      <html lang="es">
        <head>
          <title>Project Bragi</title>
          {/* Other head elements like meta tags, link tags etc. */}
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
          ></meta>
        </head>
        <body
          className={`${inter.className} flex flex-col bg-white dark:bg-black min-h-screen align-middle`}
        >
          <header className="p-4 flex justify-end">
            <ThemeToggle />
          </header>
          <Header />
          <div className="mt-20"></div>
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
