import {
  faPaintRoller,
  faLeftLong,
  faTag,
  faAward,
  faEraser,
  faPencil,
  faPlus,
  faBackspace,
  faEarListen,
  faImage,
  faMoneyBill,
  faTextHeight,
  faUpload,
  faCode,
  faExclamation,
  faEnvelope,
  faPenNib,
  faComment,
  faUser,
  faPhone,
  faFile,
  faDriversLicense,
  faMap,
  faCartShopping
} from "@fortawesome/free-solid-svg-icons";

export const Icons = {
  paintRoller: faPaintRoller,
  leftLong: faLeftLong,
  tag: faTag,
  award: faAward,
  eraser: faEraser,
  pencil: faPencil,
  plus: faPlus,
  back: faBackspace,
  earListen: faEarListen,
  image: faImage,
  money: faMoneyBill,
  text: faTextHeight,
  upload: faUpload,
  code: faCode,
  exclamation: faExclamation,
  email: faEnvelope,
  pen: faPenNib,
  comment: faComment,
  user: faUser,
  phone: faPhone,
  file: faFile,
  dni: faDriversLicense,
  map: faMap,
  shopping: faCartShopping
};