export const BARGAIN_CONTEXT = "BARGAIN"
export const FAVORITES_CONTEXT = "FAVORITES"
export const NOVELTY_CONTEXT = "NOVELTY"
export const SHOPPING_LIST_CONTEXT = "SHOPPING_LIST";
export const ORDER_CONTEXT = "ORDER"; 
export const PRODUCT_CONTEXT = "PRODUCT"

export const METHOD_GET_BARGAINS = "getBargains"
export const METHOD_GET_ACTIVE_BARGAINS = "getActiveBargains"
export const METHOD_GET_BARGAIN = "getBargain"
export const METHOD_GET_BARGAIN_BY_CODE = "getBargainByCode"
export const METHOD_TOGGLE_BARGAIN = "toggleStatusBargain"
export const METHOD_ACTION_CREATE_BARGAIN = "actionCreateBargain"
export const METHOD_CREATE_BARGAIN = "createBargain"
export const METHOD_ACTION_UPDATE_BARGAIN = "actionUpdateBargain"
export const METHOD_UPDATE_BARGAIN = "updateBargain"
export const METHOD_ACTION_DELETE_BARGAIN = "actionDeleteBargain"
export const METHOD_DELETE_BARGAIN = "deleteBargain"

export const METHOD_GET_FAVORITES = "getFavorites"
export const METHOD_CHECK_FAVORITE = "checkFavorite"
export const METHOD_CHECK_FAVORITE_LIST = "checkFavoriteList"
export const METHOD_TOGGLE_FAVORITES = "toggleFavorites"
export const METHOD_DELETE_IN_FAVORITES = "deleteProductInFavorites"

export const METHOD_GET_NOVELTIES = "getNovelties"
export const METHOD_GET_ACTIVE_NOVELTIES = "getActiveNovelties"
export const METHOD_GET_VALID_NOVELTIES = "getValidNovelties"
export const METHOD_GET_NOVELTY = "getNovelty"
export const METHOD_TOGGLE_NOVELTY = "toggleStatusNovelty"
export const METHOD_ACTION_CREATE_NOVELTY = "actionCreateNovelty"
export const METHOD_CREATE_NOVELTY = "createNovelty"
export const METHOD_ACTION_UPDATE_NOVELTY = "actionUpdateNovelty"
export const METHOD_UPDATE_NOVELTY = "updateNovelty"
export const METHOD_ACTION_DELETE_NOVELTY = "actionDeleteNovelty"
export const METHOD_DELETE_NOVELTY = "deleteNovelty"

export const METHOD_GET_SHOPPING_LIST = "getShoppingList"
export const METHOD_DELETE_PRODUCT_IN_SHOPPING_LIST = "deleteProductInShoppingList"
export const METHOD_ADD_PRODUCT_TO_SHOPPING_LIST = "addProductToShoppingList"
export const METHOD_INCREMENT_PRODUCT_IN_SHOPPING_LIST = "incrementProductInShoppingList"
export const METHOD_DECREMENT_PRODUCT_IN_SHOPPING_LIST = "decrementProductInShoppingList"

export const METHOD_GET_ORDERS = "getOrders"
export const METHOD_GET_ORDER = "getOrder"
export const METHOD_ACTION_CREATE_ORDER = "actionCreateOrder"
export const METHOD_CREATE_ORDER = "createOrder"
export const METHOD_GET_NEXT_SEQUENCE_VALUE = "getNextSequenceValue"
export const METHOD_UPDATE_ORDER_STATUS = "updateOrderStatus"
export const METHOD_GET_CLASSIFIED_PRODUCTS = "getClassifiedProducts"
export const METHOD_CREATE_MOLD_FOR_EARPHONE = "createMoldForEarphone"

export const METHOD_GET_ALL_PRODUCTS = "getAllProducts"
export const METHOD_GET_PRODUCT_BY_CATEGORY = "getProductsByCategory"
export const METHOD_GET_LATEST_PRODUCTS = "getLatestProducts"
export const METHOD_GET_RELATED_PRODUCTS = "getRelatedProducts"
export const METHOD_GET_PRODUCTS_BY_IDS = "getProductsByIds"
export const METHOD_GET_ACCESSORIES_AVAILABLE = "getAccessoriesAvailable"
export const METHOD_SEARCH_PRODUCTS = "searchProducts"
export const METHOD_GET_PRODUCT = "getProduct"
export const METHOD_GET_FILTER_INFORMATION = "getFilterInformation"
export const METHOD_ACTION_CREATE_PRODUCT = "actionCreateProduct"
export const METHOD_CREATE_PRODUCT = "createProduct"
export const METHOD_ACTION_UPDATE_PRODUCT = "actionUpdateProduct"
export const METHOD_UPDATE_PRODUCT = "updateProduct"
export const METHOD_ACTION_DELETE_PRODUCT = "actionDeleteProduct"
export const METHOD_DELETE_PRODUCT = "deleteProduct"