import type { Metadata } from "next";
import '@fortawesome/fontawesome-svg-core/styles.css';
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeToggle from "./components/themeToggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <header className="p-4 flex justify-end">
        <ThemeToggle />
      </header>
      <body className={inter.className}>{children}</body>
  
    </html>

    
  );
}
