import type { Metadata } from "next";
import '@fortawesome/fontawesome-svg-core/styles.css';
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeToggle from "./components/themeToggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <head>
          <title>Your Title</title>
          {/* Other head elements like meta tags, link tags etc. */}
          <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        </head>
        <body className={`${inter.className} flex flex-col bg-white dark:bg-black min-h-screen align-middle`}>
          <header className="p-4 flex justify-end">
            <ThemeToggle />
          </header>
          {children}
        </body>
      </html>
    );
}
