name: AudifonosXmenos - develop
on: 
  push:
    branches:
      - develop
    paths-ignore:
      - README.md
  pull_request:
    branches:
      - main
      - develop
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-env
      - run: npm run build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-env
      - run: npm run test
