name: Continuous Integration
on: 
  push:
    branches:
      - develop
    paths-ignore:
      - README.md
      - .gitattributes
      - .gitignore
      - .github/**
      - compose.yaml
      - Dockerfile
      - docs/**
      - sonar-project.properties
  pull_request:
    branches:
      - main
      - develop      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-env
      - run: npm run build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-env
      - run: npm run test
