name: AudifonosXmenos - main
on: 
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .gitattributes
      - .gitignore
      - compose.yaml
      - Dockerfile
      - docs/**
  schedule:
    - cron: '0 4 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-env
      - run: npm run build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-env
      - run: npm run test

  publish:
    runs-on: ubuntu-latest
    needs:
      - build
      - test
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}   
      
      - name: Generate tag
        id: project
        run: echo "tag=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      
      - name: Push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/audifonosxmenos:${{ steps.project.outputs.tag }}
            ${{ secrets.DOCKERHUB_USERNAME }}/audifonosxmenos:latest
